site_name: Foundation Model for Cancer Imaging Biomarkers
theme: 
  font:
    code: Roboto Mono
  name: 'material'
  favicon: 'assets/favicon.svg'
  logo: 'assets/favicon.svg'
  features:
    - content.code.copy
    - content.code.select
    - header.autohide
    - content.tooltips
    - attr_list
    - footnotes
    - navigation.tabs
    - navigation.footer

  palette:
    - scheme: slate
      accent: blue
extra_css:
  - assets/extra.css
nav:
  - 'index.md'
  - 'Getting Started': 
    - 'Pre-requisites': 'getting-started/prereqs.md'
    - 'Installation': 'getting-started/installation.md'
    - 'Package Structure': 'getting-started/package-structure.md'

  - 'User Guide':
    - 'Data Download and Preprocessing': 'user-guide/data.md'
    - 'Extracting Features & Predictions': 'user-guide/inference.md'
    - 'Replicate Analysis': 'user-guide/analysis.md'
    - 'Reproduce FM training': 'user-guide/reproduce_fm.md'
    - 'Reproduce Baselines': 'user-guide/reproduce_baselines.md'


  - 'API Reference': 'api_docs/fmcib'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
repo_url: https://github.com/AIM-Harvard/foundation-cancer-image-biomarker
copyright: <a href="https://aim.hms.harvard.edu">AIM &copy; 2023</a>
extra:
  generator: false
